spring:
  application:
    name: my-app
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml
  datasource:
    url: jdbc:postgresql://localhost:5431/postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: postgres
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  port: 8182

