spring:
  application:
    name: my-app
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.yaml
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    hikari:
      username: user
      password: password
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  servlet:
    context-path: "/"
  port: 8182

